name: Coding Standards

on: [push, pull_request]

jobs:
  coding-standards:
    name: "Apply EsLint, Stylelint and Prettier coding standards and formatting"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest 

    - name: Configure .npmrc for private npm packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_READ_TOKEN }}" > .npmrc
        echo "@effect-digital:registry=https://npm.pkg.github.com" >> .npmrc

    - name: Install node modules
      working-directory: ./
      run: bun install

    - name: Run ESLint
      working-directory: ./
      run: bun run lint:js

    - name: Run Stylelint
      working-directory: ./
      run: bun run lint:css

    - name: Format files
      working-directory: ./
      run: bun run format